version: '3.9'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: ["node", "dist/main.js"]
    env_file:
      - .env
    ports:
      - "0.0.0.0:9000:4000"  # API en puerto 9000
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
    volumes:
      - api_data:/data
      - api_logs:/app/logs  # Volumen para logs
      - ./apps/api/src:/app/src:ro
      - ./apps/api/package.json:/app/package.json:ro
      - ./apps/api/tsconfig.json:/app/tsconfig.json:ro
      - ./apps/api/tsconfig.build.json:/app/tsconfig.build.json:ro
    depends_on:
      - mongo
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    command: ["nginx", "-g", "daemon off;"]
    env_file:
      - .env
    ports:
      - "0.0.0.0:9001:80"  # Frontend en puerto 9001
    environment:
      - VITE_API_URL=http://localhost:9000
    depends_on:
      - api
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "0.0.0.0:9002:27017"  # MongoDB en puerto 9002
    volumes:
      - mongo_data:/data/db  # Datos persistentes
      - mongo_config:/data/configdb  # Configuración persistente
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=exampledb
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local
  api_data:
    driver: local
  api_logs:
    driver: local

networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16


